#!/usr/bin/env python3
"""
Master script to visualize all stages of regex compilation:
1. Syntax Tree
2. NFA (Nondeterministic Finite Automaton)
3. DFA (Deterministic Finite Automaton)
4. Minimized DFA

This script loads JSON files generated by the C++ program and creates
visualizations for each stage.
"""

import os
import sys
import subprocess


def check_file_exists(filename):
    """Check if a file exists and return True/False."""
    return os.path.exists(filename)


def run_visualization(script_name, json_file):
    """Run a visualization script if its JSON file exists."""
    if check_file_exists(json_file):
        print(f"\n{'='*60}")
        print(f"Running {script_name}...")
        print(f"{'='*60}")
        try:
            # Use subprocess to run Python script
            result = subprocess.run([sys.executable, script_name], check=False)
            if result.returncode != 0:
                print(f"Warning: {script_name} exited with code {result.returncode}")
        except Exception as e:
            print(f"Error running {script_name}: {e}")
    else:
        print(f"\nSkipping {script_name}: {json_file} not found.")


def main():
    """Main function to run all visualizations."""
    print("Regex Compiler Visualization Suite")
    print("=" * 60)
    
    # Check which JSON files exist
    files = {
        'syntax_tree.json': 'visualize_syntax_tree.py',
        'nfa.json': 'visualize_nfa.py',
        'dfa.json': 'visualize_dfa.py',
        'min_dfa.json': 'visualize_min_dfa.py'
    }
    
    found_files = []
    missing_files = []
    
    for json_file, script in files.items():
        if check_file_exists(json_file):
            found_files.append((json_file, script))
        else:
            missing_files.append(json_file)
    
    if not found_files:
        print("\nError: No JSON files found!")
        print("Please run the C++ program first to generate the JSON files.")
        sys.exit(1)
    
    print(f"\nFound {len(found_files)} JSON file(s):")
    for json_file, _ in found_files:
        print(f"  ✓ {json_file}")
    
    if missing_files:
        print(f"\nMissing {len(missing_files)} JSON file(s):")
        for json_file in missing_files:
            print(f"  ✗ {json_file}")
    
    # Run visualizations
    for json_file, script in found_files:
        run_visualization(script, json_file)
    
    print("\n" + "=" * 60)
    print("Visualization complete!")
    print("=" * 60)
    
    # List generated PNG files
    png_files = [f for f in os.listdir('.') if f.endswith('.png')]
    if png_files:
        print("\nGenerated visualization files:")
        for png_file in sorted(png_files):
            print(f"  • {png_file}")
    
    # Keep windows open
    print("\n" + "=" * 60)
    print("All visualization windows are now open.")
    print("Close all matplotlib windows to exit, or press Ctrl+C here.")
    print("=" * 60)
    
    try:
        import matplotlib.pyplot as plt
        plt.show()  # Blocking call - waits until all windows are closed
    except KeyboardInterrupt:
        print("\nVisualization interrupted by user.")


if __name__ == '__main__':
    main()